---
title: "About Me"
author: "Andrea Makamba"
categories: ["R"]
tags: ["R Markdown", "iXperience", "first post"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Alors, ça c’est une petite redaction sur moi, l’auteur de cette site.

Bonjour! My name is Andrea Makamba, and if you haven’t gathered by now, I speak both English and French. 

I am 19 years old, from Zimbabwe (Southern Africa, the country that is shaped like a teapot). I love it here. The open veld spaces, favourable weather, friendly people, what isn’t there to love about this country?
I'm currently an undergraudte student at The University of Pennsylvania- go Quakers! And what would I like to study? At the moment, I’m majoring in Systems Engineering and minoring in French & Francophone Studies and Mathematics. What can I say? I’m a nerd of the highest order.

When I’m not cooking, reading books or binge watching Adventuretime, I pass my time in the great outdoors. I play sport all year round, dividing my time between cross country, tennis and skiing. 